ARG pyversion=latest
FROM ghcr.io/anyakichi/poetry-builder:${pyversion}

RUN \
  curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - \
  && apt-get install -y nodejs \
  && rm -rf /var/lib/apt/lists/*

RUN \
  npm install -g prettier pyright
