ARG pyversion=latest
FROM ghcr.io/anyakichi/poetry-builder:${pyversion}

RUN \
  curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash - \
  && rm -rf /var/lib/apt/lists/*

RUN \
  npm install -g prettier pyright
