name: Publish Docker image
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8-slim, 3.8, 3.9-slim, 3.9, slim, latest]
    steps:
      - uses: actions/checkout@v2
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: pyversion=${{ matrix.python }}
          tags: anyakichi/poetry-builder:${{ matrix.python }}
