name: Publish Docker image
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8-slim, 3.8, 3.9-slim, 3.9, slim, latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            anyakichi/poetry-builder
            ghcr.io/anyakichi/poetry-builder
          tags: ${{ matrix.python }}
      - uses: docker/metadata-action@v3
        id: meta-full
        with:
          images: |
            anyakichi/poetry-builder
            ghcr.io/anyakichi/poetry-builder
          tags: ${{ matrix.python }}-full
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: pyversion=${{ matrix.python }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.full
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: pyversion=${{ matrix.python }}
          tags: ${{ steps.meta-full.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
